services:
  # SmartLipad Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smartlipad_backend
    restart: unless-stopped
    ports:
      - "${API_PORT:-8000}:8000"
    env_file: .env
    volumes:
      - ./backend:/app/backend
      - ./logs:/app/logs
      - backend_cache:/app/.cache
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  backend_cache:
    driver: local